module.exports.authService = require('./auth.service')
module.exports.taskService = require('./task.service')
module.exports.tokenService = require('./token.service')
module.exports.boardService = require('./user.service')
module.exports.boardService = require('./board.service')
module.exports.columnService = require('./column.service')
module.exports.cardService = require('./card.service')
