module.exports.authController = require('./auth.controller')
module.exports.taskController = require('./task.controller')
module.exports.boardController = require('./board.controller')
module.exports.columnController = require('./column.controller')
module.exports.cardController = require('./card.controller')
